# Generated by Django 2.2.4 on 2019-09-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_ordermanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderManager',
        ),
    ]
